import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#3f4944",
        "primary-fixed-dim": "#8bd6b6",
        "on-primary-fixed": "#002116",
        "surface-container-lowest": "#ffffff",
        outline: "#6f7973",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "on-tertiary-fixed-variant": "#73332f",
        "on-error-container": "#93000a",
        "outline-variant": "#bec9c2",
        "secondary-fixed-dim": "#bdc7db",
        "surface-tint": "#1b6b51",
        "inverse-primary": "#8bd6b6",
        "on-tertiary-fixed": "#3b0908",
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "on-background": "#191c1d",
        "secondary-fixed": "#d9e3f7",
        "surface-bright": "#f8f9fa",
        surface: "#f8f9fa",
        "primary-container": "#065f46",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#ffb4ad",
        tertiary: "#652925",
        "tertiary-fixed-dim": "#ffb3ac",
        "on-primary-container": "#8bd6b7",
        "tertiary-container": "#823f3a",
        "secondary-container": "#d6e0f4",
        "on-primary-fixed-variant": "#00513b",
        "on-secondary-fixed-variant": "#3d4757",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#121c2a",
        "surface-container-high": "#e7e8e9",
        "on-secondary-container": "#596374",
        "inverse-on-surface": "#f0f1f2",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadb",
        secondary: "#555f70",
        primary: "#004532",
        background: "#f8f9fa",
        error: "#ba1a1a",
        "primary-fixed": "#a6f2d1",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#ffdad6",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "Manrope", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        editorial: "0 32px 64px -12px rgba(25, 28, 29, 0.04)",
        "editorial-lg": "0 48px 80px -16px rgba(0, 69, 50, 0.08)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
